RMS.Web.UI/Areas/Admin/Models/Vacancy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RMS.Web.UI.Areas.Admin.Models
{
    public class Vacancy
    {

        public  List<string> JobTitle { get; set; }

       
    }
}

RMS.Web.UI/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RMS.Web.UI.Models
{
    public class AccountModels
    {
        [Required(ErrorMessage = "Please Enter email Address")]
        [Display(Name = "UserName")]
        [RegularExpression(".+@.+\\..+", ErrorMessage = "Please Enter Correct email Address")]
        public string UserName { get; set; }    
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

RMS.Web.UI/Models/UserContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RMS.Web.UI.Authentication;

namespace RMS.Web.UI.Models
{
    public class UserContext
    {
        private readonly CustomPrincipal _customPrincipal;
        public UserContext(CustomPrincipal customPrincipal)
        {
            _customPrincipal = customPrincipal;
        }
        public int UserId
        {
            get { return _customPrincipal.UserId; }
        }
        public string Email
        {
            get { return _customPrincipal.Identity.Name; }
        }
        public bool IsAuthenticated
        {
            get { return _customPrincipal != null && _customPrincipal.Identity.IsAuthenticated; }
        }
    }
}

RMS.Web.UI/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Web.UI.Areas.Admin.Controllers
{
     [Authorize]
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

RMS.Web.UI/Areas/Admin/Controllers/VacancyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMS.Business;
using RMS.Models;
using RMS.Business.Service;

namespace RMS.Web.UI.Areas.Admin.Controllers
{
    public class VacancyController : Controller
    {
      UserService userservice = null;
          public VacancyController()
        {
            userservice = new UserService();
        }

        [HttpGet]
        public ActionResult Create()
        {
            Vacancy vacancies = new Vacancy();

            var data = userservice.GetJobLocation();
            ViewBag.locations = new SelectList(data, "Id", "locations");
            return View(vacancies);
        }

        [HttpPost]
        public ActionResult Create(Vacancy vacancies)
        {
            userservice.CreateVacancy(vacancies);
            return View(vacancies);
        }


        [HttpGet]
        public ActionResult GetJobTitle(string query)
        {
            var jobTitle = userservice.GetJobTitle();
            jobTitle = jobTitle.Where(p => p.JobTitle.StartsWith(query, StringComparison.CurrentCultureIgnoreCase)).ToList();
            return Json(jobTitle, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetJobLocation()
        {
            var data = userservice.GetJobLocation();

            return Json(data, JsonRequestBehavior.AllowGet);
          
        }



    }
}

RMS.Web.UI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMS.Web.UI.Models;
using RMS.Business.Interface;
using RMS.Web.UI.ViewModel;
using RMS.Business;
using RMS.Business.Service;
using RMS.Utility;
using RMS.Models;
using RMS.Web.UI.Authentication;
using System.Web.Security;

namespace RMS.Web.UI.Controllers
{
    public class AccountController : BaseController
    {
       UserService userservice = null;
        Email email = null;
       FormsAuthentications authService = null;

       public AccountController()
        {
          userservice=new UserService();
          email=   new Email();
          authService = new FormsAuthentications();
        }


        [AllowAnonymous]
       public ActionResult Login()
       {
           if (UserContext.IsAuthenticated)
               return Redirect("Home");

            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
               var user = authService.Login(login.Email, login.Password, login.RememberMe);
                if (user.Status == (int)LoginStatusEnum.InvalidPassword)
                {
                    ModelState.AddModelError("Password", "Invalid password entered");
                }
                else if (user.Status == (int)LoginStatusEnum.InvalidEmail)
                {
                    ModelState.AddModelError("Email", "This email id does not exist");

                }
                else if(user.IsAdmin==true)
                {
                  //  return Redirect("Home");
                   return RedirectToAction("index", "home", new { area = "Admin" });
                }
             }
              return View(login);
        }

        [HttpPost]
        public ActionResult ForgotPassword(Employee employeeInstance)
        {
          if (ModelState.IsValid)
            {
                var user = userservice.GetUserPassword(employeeInstance.EmailId);
                if (user.Status==(int)LoginStatusEnum.Success)
                {
                    email.SendMail(user);
                    employeeInstance.Message = "true";
                }
                else
                {
                    employeeInstance.Message = "false";
                }
            }
            return Json(employeeInstance);
        }


        
        public ActionResult LogOut()
        {
            authService.Logout();
            return RedirectToAction("Login");

        }

    }
}

RMS.Web.UI/Controllers/BaseController.cs
using RMS.Web.UI.Authentication;
using RMS.Web.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Web.UI.Controllers
{

    public class BaseController : Controller
    {
        
        private UserContext _userContext;
        protected virtual new CustomPrincipal User
        {
            get { return HttpContext.User as CustomPrincipal; }
        }

        public UserContext UserContext
        {
            get { return _userContext ?? (_userContext = new UserContext(User)); }
        }




    }
}

RMS.Web.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMS.Web.UI.Controllers
{
      [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }   
    }
}

RMS.Web.UI/Areas/Admin/Views/Home/Index.cshtml
@{
   
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

RMS.Web.UI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">





    <link href="~/Areas/Admin/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="~/Areas/Admin/Content/jquery-jvectormap-1.2.2.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/skins/_all-skins.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/StyleSheet.css" rel="stylesheet" />



</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="" class="logo"></a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li>
                            @using (Html.BeginForm("LogOut", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
                            {
                               <button type="submit" class="log-out-btn">Log Out</button>

                            }
                        </li>                       
                             
                    </ul>
                </div>
            </nav>
        </header>
   
    <aside class="main-sidebar">
        <section class="sidebar">
            <ul class="sidebar-menu">
                <li class="active treeview">
                    <a href="#">
                        @*<i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>*@
                    </a>
                    <ul class="treeview-menu">
                        @*<li><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>*@
                        <li>    </li>

                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-pie-chart"></i>
                        <span>Vacancy</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li>@Html.ActionLink("Create Vacancy", "Create", "Vacancy")</li>
                        <li>@Html.ActionLink("View Vacancies", "View", "Vacancy")</li>
                        @*<li><a href="#"><i class="fa fa-circle-o"></i> Flot</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Inline charts</a></li>*@
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-laptop"></i>
                        <span>Prospects</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li>@Html.ActionLink("Create Prospect", "CreateProspect", "Prospects")</li>
                        <li>@Html.ActionLink("View Prospects", "ViewProspects", "Prospects")</li>
                        @*<li><a href="#"><i class="fa fa-circle-o"></i> Buttons</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Sliders</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Timeline</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Modals</a></li>*@
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-edit"></i> <span>Manage Users</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li>@Html.ActionLink("Create Employee", "CreateEmployee", "ManageUsers")</li>
                        <li>@Html.ActionLink("Candidate/Employee List", "ViewDetails", "ManageUsers")</li>
                        @*<li><a href="#"><i class="fa fa-circle-o"></i> Editors</a></li>*@
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-table"></i> <span>Recruitment Process</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li>@Html.ActionLink("Recruitment Process", "RecruitmentProcess", "RecruitmentProcess")</li>
                        @*<li><a href="#"><i class="fa fa-circle-o"></i> Data tables</a></li>*@
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-folder"></i> <span>Interview Details</span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li>@Html.ActionLink("Interview Details", "Interview", "Interview")</li>
                        <li>@Html.ActionLink("Reschedule Request", "RescheduleRequest", "Interview")</li>
                        <li>@Html.ActionLink("Interview Report", "InterviewReport", "Interview")</li>
                        @*<li><a href="#"><i class="fa fa-circle-o"></i> Register</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Blank Page</a></li>*@
                    </ul>
                </li>
                @*<li class="treeview">
                        <a href="#">
                            <i class="fa fa-share"></i> <span>Multilevel</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                                    <li>
                                        <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                                        <ul class="treeview-menu">
                                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                        </ul>
                    </li>*@
                <li class="header">LABELS</li>
                <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
                <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
                <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">


            <!-- Content Header (Page header) -->
            <section class="content-header"></section>
            <!-- Main content -->
            <section class="content">
                <!-- Info boxes -->
                @RenderBody()


            </section>



            <div class="control-sidebar-bg"></div>
        </div>

        <script src="~/Areas/Admin/Scripts/jQuery-2.1.4.min.js"></script>
        <script src="~/Areas/Admin/Scripts/bootstrap.js"></script>
        <script src="~/Areas/Admin/Scripts/fastclick.min.js"></script>
        <script src="~/Areas/Admin/Scripts/app.min.js"></script>

        <script src="~/Areas/Admin/Scripts/jquery.sparkline.min.js"></script>
        <script src="~/Areas/Admin/Scripts/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="~/Areas/Admin/Scripts/jquery-jvectormap-world-mill-en.js"></script>

        <script src="~/Areas/Admin/Scripts/jquery.slimscroll.min.js"></script>
        <script src="~/Areas/Admin/Scripts/Chart.min.js"></script>







    </div>



</body>
</html>

RMS.Web.UI/Areas/Admin/Views/Vacancy/Create.cshtml
@model RMS.Models.Vacancy
<html>
<body>
    @using (Html.BeginForm("Create", "Vacancy", FormMethod.Post))
    {
      <section class="content-header">
            <h1>Create Vacancy</h1>
       </section>
        <section class="content">
            <div class="Create Vacancy-Form">
            
                    <div class="row">
                        <div class="col-md-6">
                              <div class="form-group ">
                              <div class="form-group log-status">
                                    <label for="JobTitle" class="col-sm-4 control-label">Job-Title</label>
                                    <input type="text" id="search" placeholder="JobTitle" />
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="row">
                       <div class="col-md-6">
                            <div class="form-group log-status">
                                <label for="JobDescription" class="col-sm-4 control-label">Job-Description</label>
                                @Html.TextAreaFor(m => m.JobDescription, new { @id = "JobDescription", @class = "col-sm-8", @placeholder = "JobDescription" })
                                <div id="JobDescription" style="color:red">
                                    @Html.ValidationMessageFor(m => m.JobDescription)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label for="Keywords" class="col-sm-4 control-label">Keywords</label>
                                @Html.TextAreaFor(m => m.Keywords, new { @id = "Keywords", @class = "col-sm-8", @placeholder = "Keywords" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label for="NumberOfPositions" class="col-sm-4 control-label">Number Of Positions</label>
                                @Html.TextBoxFor(m => m.NumberOfPositions, new { @id = "NumberOfPositions", @class = " col-sm-8", @placeholder = "NumberOfPositions" })
                            </div>
                        </div>
                    </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label for="NumberOfPositions" class="col-sm-4 control-label">Location</label>
                            
                            @Html.DropDownList("locations", "select")
                         </div>
                    </div>
                </div>
          
            
                <button type="submit">Add Job</button>
               </div>
        </section>
    }

    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

</body>
</html>




<script>
    var id = $('#search').val();
    var url = "/Vacancy/GetJobTitle" + id;
    $('#search').autocomplete({
        source: function (request, response) {
            $.ajax({
                url: url,
                data: { query: request.term },
                dataType: 'json',
                type: 'GET',
                success: function (data) {
                    response($.map(data, function (item) {
                       return {
                           label: item.JobTitle,
                            value: item.Id
                        }
                    }));
                },
                error: function(error)
                {
                    alert("error")
                }
            })
        },
        select: function (event, ui) {
            $('#search').val(ui.item.label);
            $('#Id').val(ui.item.value);
            return false;
        },
        minLength: 1
    });
</script>

RMS.Web.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    
    }



<div id="wrapper" style="text-align: center">
    <h1>Welcome To Ex2 RMS</h1>
</div>



@if (Request.IsAuthenticated)
{
    <li>
         @using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { id = "logoutForm" }))
        {
            @Html.AntiForgeryToken()
            <a href="javascript:document.getElementById('logoutForm').submit()">Log Out</a>

    
        }
    </li>
}
else
{
    <ul>
            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>

    

    </ul>
}

RMS.Web.UI/Views/Shared/_ForgotPassword.cshtml
@model RMS.Web.UI.ViewModel.LoginViewModel
<script src="~/Scripts/application.js"></script>
<!-- Button HTML (to Trigger Modal) -->
<div class="modal fade" id="forget-password-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" onclick="ClearForgotFilledData();">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Forgot password</h4>
            </div>
            <div class="modal-body">
                <div class="login-form-row">
                    <div class="user-input-fileds">
                        <input type="text" placeholder="Please enter registered email" class="form-control" name="EmailId" id="emailtxt">
                        @Html.ValidationMessageFor(n => n.employee)
                        <div><ul id="valid" /></div>
                    </div>
                </div>
                <div class="login-form-row">

                    <div class="user-input-fileds">
                        @*<input type="submit" id="forgot-btn" value="Forgot Password" class="forget-password-btn" onclick="SubmitForgotPassword();">*@
                        <input type="submit" id="forgot-btn" value="Forgot Password" class="forget-password-btn" onclick="return GetUserPassword();">
                    </div>
                </div>
           </div>
        </div>
    </div>
</div>

RMS.Web.UI/Views/Shared/_Layout.cshtml
@RenderBody();